#!/usr/bin/env bash
# Install helper for dfrun.
#
# Places a launcher on PATH (~/.local/bin/dfrun) so the tool runs as a single
# command, and a Desktop shortcut (~/Desktop/dfrun.desktop) that opens a
# terminal running it. British English; no em dashes.
#
# Usage:  bash install.sh        (or: make install)

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
DESKTOP_DIR="${HOME}/Desktop"
PYTHON="${PYTHON:-python3}"

# 1. Launcher on PATH.
mkdir -p "${BIN_DIR}"
WRAPPER="${BIN_DIR}/dfrun"
cat > "${WRAPPER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh; runs dfrun from its repository checkout.
exec "${PYTHON}" "${REPO_DIR}/dfrun.py" "\$@"
EOF
chmod +x "${WRAPPER}"
echo "Installed launcher: ${WRAPPER}"

case ":${PATH}:" in
  *":${BIN_DIR}:"*)
    : ;;  # already on PATH
  *)
    echo "NOTE: ${BIN_DIR} is not on your PATH. Add this to ~/.bashrc:"
    echo "      export PATH=\"${BIN_DIR}:\$PATH\""
    ;;
esac

# 2. Desktop shortcut.
if [ -d "${DESKTOP_DIR}" ]; then
  DESKTOP_FILE="${DESKTOP_DIR}/dfrun.desktop"
  cat > "${DESKTOP_FILE}" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=dfrun (DeepFaune)
Comment=Run the DeepFaune camera-trap classifier
Exec=gnome-terminal -- bash -lc '"${WRAPPER}"; echo; read -n 1 -s -r -p "Press any key to close..."'
Icon=${REPO_DIR}/icons/logoINEE.png
Terminal=false
Categories=Science;Utility;
EOF
  chmod +x "${DESKTOP_FILE}"
  # Best-effort: mark trusted so GNOME launches it without the warning.
  gio set "${DESKTOP_FILE}" metadata::trusted true 2>/dev/null || true
  echo "Installed Desktop shortcut: ${DESKTOP_FILE}"
  echo "First time only: right-click the icon and choose 'Allow Launching' so GNOME trusts it."
else
  echo "No ${DESKTOP_DIR}; skipped the Desktop shortcut."
fi

# 3. Optional runtime extras for the live readout.
if ! "${PYTHON}" -c "import rich, psutil" 2>/dev/null; then
  echo "NOTE: the live readout needs 'rich' and 'psutil'. Install them with:"
  echo "      ${PYTHON} -m pip install rich psutil"
fi

echo "Done. Run 'dfrun' to start (or use the Desktop shortcut)."
