#!/usr/bin/env bash
# Install helper for dfrun.
#
# Places a launcher on PATH (~/.local/bin/dfrun) so the tool runs as a single
# command, and a Desktop shortcut (~/Desktop/dfrun.desktop) that opens a
# terminal running it. British English; no em dashes.
#
# Usage:  bash install.sh        (or: make install)

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
DESKTOP_DIR="${HOME}/Desktop"

# Find the Python that runs DeepFaune, by full path, so the launcher and the
# Desktop icon work without activating anything first. An explicit PYTHON=...
# always wins. Otherwise candidates are tried in order - the active virtual
# environment, a .venv or venv inside the repo, the Python an existing
# launcher already uses, then the system python3 - and the first that can
# import torch is chosen. Torch is the test because it is what separates the
# DeepFaune environment from a bare system Python; picking the wrong one here
# once broke the launcher when the installer was re-run outside the venv.
find_python() {
  candidates=""
  [ -n "${VIRTUAL_ENV:-}" ] && candidates="${candidates}${VIRTUAL_ENV}/bin/python3
"
  candidates="${candidates}${REPO_DIR}/.venv/bin/python3
${REPO_DIR}/venv/bin/python3
"
  if [ -f "${BIN_DIR}/dfrun" ]; then
    prev="$(sed -n 's/^exec "\(.*python[^"]*\)".*/\1/p' "${BIN_DIR}/dfrun" | head -n 1)"
    [ -n "${prev}" ] && candidates="${candidates}${prev}
"
  fi
  candidates="${candidates}$(command -v python3 || echo python3)
"
  first_existing=""
  printf '%b' "${candidates}" | while IFS= read -r c; do
    [ -n "${c}" ] && [ -x "${c}" ] || continue
    if "${c}" -c "import torch" >/dev/null 2>&1; then printf '%s
' "${c}"; return 0; fi
  done | head -n 1
}
if [ -z "${PYTHON:-}" ]; then
  PYTHON="$(find_python || true)"
  if [ -z "${PYTHON}" ]; then
    # Nothing can import torch; take the first candidate that exists at all.
    for c in "${VIRTUAL_ENV:+${VIRTUAL_ENV}/bin/python3}"              "${REPO_DIR}/.venv/bin/python3" "${REPO_DIR}/venv/bin/python3"              "$(command -v python3 || echo python3)"; do
      [ -n "${c}" ] && [ -x "${c}" ] && { PYTHON="${c}"; break; }
    done
    PYTHON="${PYTHON:-python3}"
    echo "WARNING: no Python with torch found; using ${PYTHON}."
    echo "         The worker needs the DeepFaune environment. If it lives elsewhere,"
    echo "         re-run as: PYTHON=/path/to/venv/bin/python3 bash install.sh"
  fi
fi
echo "Using Python: ${PYTHON}"
if ! "${PYTHON}" -c "import torch" >/dev/null 2>&1; then
  echo "WARNING: ${PYTHON} cannot import torch; the classifier will not run with it."
fi

# 1. Launcher on PATH.
mkdir -p "${BIN_DIR}"
WRAPPER="${BIN_DIR}/dfrun"
cat > "${WRAPPER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh; runs dfrun from its repository checkout.
exec "${PYTHON}" "${REPO_DIR}/dfrun.py" "\$@"
EOF
chmod +x "${WRAPPER}"
echo "Installed launcher: ${WRAPPER}"

case ":${PATH}:" in
  *":${BIN_DIR}:"*)
    : ;;  # already on PATH
  *)
    echo "NOTE: ${BIN_DIR} is not on your PATH. Add this to ~/.bashrc:"
    echo "      export PATH=\"${BIN_DIR}:\$PATH\""
    ;;
esac

# 2. Desktop shortcut.
if [ -d "${DESKTOP_DIR}" ]; then
  DESKTOP_FILE="${DESKTOP_DIR}/dfrun.desktop"
  cat > "${DESKTOP_FILE}" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=Run DeepFaune
Comment=Run the DeepFaune camera-trap classifier
Exec=gnome-terminal -- bash -lc '"${WRAPPER}"; echo; read -n 1 -s -r -p "Press any key to close..."'
Icon=${REPO_DIR}/icons/logoINEE.png
Terminal=false
Categories=Science;Utility;
EOF
  chmod +x "${DESKTOP_FILE}"
  # Best-effort: mark trusted so GNOME launches it without the warning.
  gio set "${DESKTOP_FILE}" metadata::trusted true 2>/dev/null || true
  echo "Installed Desktop shortcut: ${DESKTOP_FILE}"
  echo "First time only: right-click the icon and choose 'Allow Launching' so GNOME trusts it."

  # Friendly plain-English guide on the Desktop. A symlink into the repo, so
  # every self-update refreshes it with no copying.
  if [ -f "${REPO_DIR}/docs/USER_GUIDE.html" ]; then
    ln -sfn "${REPO_DIR}/docs/USER_GUIDE.html" "${DESKTOP_DIR}/How_to_use_dfrun.html"
    echo "Linked guide: ${DESKTOP_DIR}/How_to_use_dfrun.html -> repo copy"
  fi

  # Dashboard and result filter: opens in a browser, reads the master CSV
  # locally. Also a symlink, so it always matches the installed version.
  if [ -f "${REPO_DIR}/dashboard_and_filter.html" ]; then
    ln -sfn "${REPO_DIR}/dashboard_and_filter.html" "${DESKTOP_DIR}/dashboard_and_filter.html"
    echo "Linked dashboard and filter: ${DESKTOP_DIR}/dashboard_and_filter.html -> repo copy"
    rm -f "${DESKTOP_DIR}/filter_master_results.html" "${DESKTOP_DIR}/deepfaune_dashboard.html"
  fi
else
  echo "No ${DESKTOP_DIR}; skipped the Desktop shortcut."
fi

# 3. Runtime extras for the live screen.
if ! "${PYTHON}" -c "import rich, psutil" 2>/dev/null; then
  echo "NOTE: the live screen needs 'rich' and 'psutil'. Install with:"
  echo "      ${PYTHON} -m pip install rich psutil"
fi

echo "Done. Run 'dfrun' to start (or use the Desktop shortcut)."
